// Lesson 11: Weather & Seasons
// Generated by: thai-lesson-builder agent
// Ready to add to lesson data

export const lesson11 = {
  id: 11,
  title: "Weather & Seasons",
  titleHe: "מזג אוויר ועונות",
  description: "Learn to talk about weather conditions and Thailand's seasons",
  descriptionHe: "למדו לדבר על מזג אוויר ועונות השנה בתאילנด",
  icon: "🌦️",

  phrases: [
    {
      id: 1,
      thai: "อากาศร้อน",
      pronunciation: "aa-gàat rón",
      hebrew: "מזג אוויר חם",
      english: "Hot weather",
      audioFile: null,
      usageTip: "Thailand is hot year-round, but especially March-May"
    },
    {
      id: 2,
      thai: "ฝนตก",
      pronunciation: "fǒn dtòk",
      hebrew: "יורד גשם",
      english: "It's raining",
      audioFile: null,
      usageTip: "Rainy season is June-October, but brief showers possible anytime"
    },
    {
      id: 3,
      thai: "อากาศเย็น",
      pronunciation: "aa-gàat yen",
      hebrew: "מזג אוויר קריר",
      english: "Cool weather",
      audioFile: null,
      usageTip: "'Cool' in Thailand means 20-25°C (68-77°F) - not cold by Western standards"
    },
    {
      id: 4,
      thai: "แดดจัด",
      pronunciation: "dɛ̀ɛt jàt",
      hebrew: "שמש חזקה",
      english: "Strong sun / Very sunny",
      audioFile: null,
      usageTip: "Always carry sunscreen! Thai sun is intense 10am-3pm"
    },
    {
      id: 5,
      thai: "อากาศดีวันนี้",
      pronunciation: "aa-gàat dii wan-níi",
      hebrew: "מזג אוויר נחמד היום",
      english: "Nice weather today",
      audioFile: null,
      usageTip: "Great conversation starter with tuk-tuk drivers and vendors"
    },
    {
      id: 6,
      thai: "จะฝนตกไหม",
      pronunciation: "jà fǒn dtòk mǎi",
      hebrew: "יירד גשם?",
      english: "Will it rain?",
      audioFile: null,
      usageTip: "Useful before planning outdoor activities"
    },
    {
      id: 7,
      thai: "หน้าฝน",
      pronunciation: "nâa fǒn",
      hebrew: "עונת הגשמים",
      english: "Rainy season",
      audioFile: null,
      usageTip: "Also called มรสุม (mon-ra-sǔm) - monsoon season"
    }
  ],

  dialogue: {
    title: "Checking Weather Before a Day Trip",
    titleHe: "בדיקת מזג האוויר לפני טיול יומי",
    scenario: "You're at a hotel asking the receptionist about weather for your planned trip to the beach",
    scenarioHe: "את/ה במלון ושואל את פקיד הקבלה על מזג האוויר לטיול המתוכנן לחוף",
    lines: [
      {
        speaker: "You",
        speakerHe: "את/ה",
        thai: "วันนี้อากาศเป็นยังไงครับ",
        pronunciation: "wan-níi aa-gàat bpen yang-ngai khráp",
        hebrew: "איך מזג האוויר היום?",
        english: "How's the weather today?"
      },
      {
        speaker: "Receptionist",
        speakerHe: "פקיד הקבלה",
        thai: "วันนี้อากาศดีค่ะ แดดจัดนิดหน่อย",
        pronunciation: "wan-níi aa-gàat dii khâ, dɛ̀ɛt jàt nít-nòi",
        hebrew: "מזג האוויר טוב היום, שמש קצת חזקה",
        english: "The weather is nice today, a bit sunny"
      },
      {
        speaker: "You",
        speakerHe: "את/ה",
        thai: "พรุ่งนี้จะฝนตกไหมครับ",
        pronunciation: "phrûng-níi jà fǒn dtòk mǎi khráp",
        hebrew: "יירד גשם מחר?",
        english: "Will it rain tomorrow?"
      },
      {
        speaker: "Receptionist",
        speakerHe: "פקיד הקבלה",
        thai: "อาจจะฝนตกตอนบ่ายค่ะ",
        pronunciation: "àat jà fǒn dtòk dtɔɔn bàai khâ",
        hebrew: "אולי יירד גשם אחר הצהריים",
        english: "It might rain in the afternoon"
      },
      {
        speaker: "You",
        speakerHe: "את/ה",
        thai: "งั้นไปชายหาดตอนเช้าดีกว่าครับ",
        pronunciation: "ngán bpai chaai-hàat dtɔɔn cháo dii gwàa khráp",
        hebrew: "אז עדיף ללכת לחוף בבוקר",
        english: "Then it's better to go to the beach in the morning"
      },
      {
        speaker: "Receptionist",
        speakerHe: "פקיד הקבלה",
        thai: "ใช่ค่ะ อย่าลืมทาครีมกันแดดนะคะ",
        pronunciation: "châi khâ, yàa lʉʉm thaa khriim gan-dɛ̀ɛt ná khá",
        hebrew: "נכון, אל תשכחו למרוח קרם הגנה",
        english: "Yes, don't forget to apply sunscreen"
      }
    ]
  },

  exercises: [
    {
      id: 1,
      type: "multiple-choice",
      question: "How do you say 'It's raining' in Thai?",
      questionHe: "איך אומרים 'יורד גשם' בתאית?",
      options: ["ฝนตก", "อากาศร้อน", "แดดจัด", "อากาศเย็น"],
      correctAnswer: 0,
      explanation: "ฝนตก (fǒn dtòk) literally means 'rain falls' - it's raining",
      explanationHe: "ฝนตก (fon tok) אומר מילולית 'גשם נופל' - יורד גשם"
    },
    {
      id: 2,
      type: "multiple-choice",
      question: "What does 'แดดจัด' mean?",
      questionHe: "מה המשמעות של 'แดดจัด'?",
      options: ["Cold weather", "Strong sun", "Light rain", "Cloudy"],
      correctAnswer: 1,
      explanation: "แดดจัด (dɛ̀ɛt jàt) means strong sun or very sunny",
      explanationHe: "แดดจัด (det jat) משמעותו שמש חזקה או שמשי מאוד"
    },
    {
      id: 3,
      type: "fill-in-blank",
      question: "Complete: จะ_____ไหม (Will it rain?)",
      questionHe: "השלימו: จะ_____ไหม (יירד גשם?)",
      options: ["ฝนตก", "อากาศ", "ร้อน", "เย็น"],
      correctAnswer: 0,
      explanation: "จะฝนตกไหม (jà fǒn dtòk mǎi) - Will it rain?",
      explanationHe: "จะฝนตกไหม (ja fon tok mai) - יירד גשם?"
    },
    {
      id: 4,
      type: "multiple-choice",
      question: "Thailand's cool season is approximately:",
      questionHe: "העונה הקרירה של תאילנד היא בערך:",
      options: [
        "March-May",
        "June-October",
        "November-February",
        "Year-round"
      ],
      correctAnswer: 2,
      explanation: "November-February is cool season (20-25°C), though still warm by many standards",
      explanationHe: "נובמבר-פברואר היא העונה הקרירה (20-25°C), אם כי עדיין חמה לפי מדדים רבים"
    },
    {
      id: 5,
      type: "matching",
      question: "Match Thai weather words to their meanings:",
      questionHe: "התאימו מילים תאיות למזג אוויר למשמעותן:",
      options: [
        "อากาศร้อน → Hot weather",
        "ฝนตก → Raining",
        "อากาศเย็น → Cool weather",
        "หน้าฝน → Rainy season"
      ],
      correctAnswer: 0,
      explanation: "All matches are correct!",
      explanationHe: "כל ההתאמות נכונות!"
    },
    {
      id: 6,
      type: "multiple-choice",
      question: "What should you say as a conversation starter about nice weather?",
      questionHe: "מה כדאי להגיד כפתיח שיחה על מזג אוויר נחמד?",
      options: [
        "จะฝนตกไหม",
        "อากาศดีวันนี้",
        "หน้าฝน",
        "แดดจัด"
      ],
      correctAnswer: 1,
      explanation: "อากาศดีวันนี้ (aa-gàat dii wan-níi) - Nice weather today! Great for small talk",
      explanationHe: "อากาศดีวันนี้ (akat di wan ni) - מזג אוויר נחמד היום! מצוין לשיחת חולין"
    }
  ],

  culturalTips: [
    {
      tip: "Thailand has 3 seasons: Hot (March-May 35-40°C), Rainy (June-October with afternoon showers), and Cool (November-February 20-28°C). The 'cool' season is the best time to visit!",
      tipHe: "לתאילנד יש 3 עונות: חמה (מרץ-מאי 35-40°C), גשומה (יוני-אוקטובר עם ממטרים אחה״צ), וקרירה (נובמבר-פברואר 20-28°C). העונה ה'קרירה' היא הזמן הטוב ביותר לביקור!"
    },
    {
      tip: "Don't let 'rainy season' scare you away - it usually rains for 1-2 hours in the afternoon, then clears up. Hotels are cheaper and attractions less crowded!",
      tipHe: "אל תיתנו ל'עונת הגשמים' להפחיד אתכם - בדרך כלל יורד גשם ל-1-2 שעות אחר הצהריים ואז מתבהר. המלונות זולים יותר והאטרקציות פחות צפופות!"
    },
    {
      tip: "Thais consider 25°C (77°F) as 'cold' and will wear jackets. You'll see locals in winter clothes while tourists are in shorts - it's completely normal!",
      tipHe: "תאים מחשיבים 25°C (77°F) כ'קר' וילבשו ז'קטים. תראו מקומיים בבגדי חורף בזמן שתיירים בשורטים - זה לגמרי נורמלי!"
    },
    {
      tip: "Air conditioning in malls, restaurants and transportation can be VERY cold (18-20°C). Always carry a light jacket or scarf, even in hot season!",
      tipHe: "מיזוג אוויר בקניונים, מסעדות ותחבורה יכול להיות קר מאוד (18-20°C). תמיד קחו ז'קט קל או צעיף, גם בעונה החמה!"
    }
  ]
};

// Export type for TypeScript
export type Lesson = typeof lesson11;
