// Function to send welcome email to new subscribers
// Generated by: newsletter-composer agent
// Add this to server/emailService.ts

import { resend } from './emailService'; // Assuming resend is already configured
import * as fs from 'fs';
import * as path from 'path';

interface WelcomeEmailParams {
  email: string;
  name?: string;
}

export async function sendWelcomeEmail({ email, name }: WelcomeEmailParams) {
  try {
    // Read the HTML template
    const templatePath = path.join(__dirname, '../email-template-welcome.html');
    let htmlContent = fs.readFileSync(templatePath, 'utf-8');

    // Personalize if name is provided
    if (name) {
      htmlContent = htmlContent.replace(
        'שלום וברוכים הבאים!',
        `שלום ${name} וברוכים הבאים!`
      );
      htmlContent = htmlContent.replace(
        'Hello and Welcome!',
        `Hello ${name} and Welcome!`
      );
    }

    // Send email via Resend
    const result = await resend.emails.send({
      from: 'Thailand Hayom <newsletter@thailand-hayom.com>',
      to: email,
      subject: '🇹🇭 ברוכים הבאים לתאילנד היום | Welcome to Thailand Hayom',
      html: htmlContent,
      tags: [
        { name: 'type', value: 'welcome' },
        { name: 'tier', value: 'free' }
      ],
      // Add unsubscribe link (Resend will replace {{unsubscribe_url}})
      headers: {
        'List-Unsubscribe': '<{{unsubscribe_url}}>',
      }
    });

    console.log('[Email] Welcome email sent:', result.id);
    return { success: true, emailId: result.id };

  } catch (error) {
    console.error('[Email] Failed to send welcome email:', error);
    return { success: false, error };
  }
}

// Usage in newsletterRouter.ts:
//
// import { sendWelcomeEmail } from './emailService';
//
// subscribe: publicProcedure
//   .input(z.object({ email: z.string().email(), name: z.string().optional() }))
//   .mutation(async ({ input }) => {
//     const db = await getDb();
//
//     // Add to database
//     await db.insert(newsletterSubscribers).values({
//       email: input.email,
//       name: input.name,
//       tier: 'free',
//       status: 'active'
//     });
//
//     // Send welcome email
//     await sendWelcomeEmail({
//       email: input.email,
//       name: input.name
//     });
//
//     return { success: true };
//   })

// Test sending locally:
//
// sendWelcomeEmail({
//   email: 'test@example.com',
//   name: 'David'
// });
